### ISSUE TITLE
Any plans for a version with a GPS/GPRS module like SIM808 or SIM868?

### ISSUE THREAD

**Issue by ianwillianb** [Xinyuan-LilyGO/TTGO-T-Call#1]

**Comment by LilyGO** [comment]
Yes, our T-watch is designing the expansion board module of SIM808.

**Comment by manuelkwizera** [comment]
@LilyGO, is the board available yet?

**Comment by lewisxhe** [comment]
No, this board is no longer available. We recommend using the A7670 series.

**Comment by lewisxhe** [comment]
Can you detect the keyboard now?
