### ISSUE TITLE
Which board to select in Arduino IDE?

### ISSUE THREAD

**Issue by timnoel** [Xinyuan-LilyGO/TTGO-T-Call#18]
I am looking to use the TTGO T-Call board, and have written code.  However, there does not seem to be any boards available in Arduino IDE.

Is there a board repository for the TTGO T-Call board?  If no, then what other Arduino board can I select so that the code can be uploaded to the T-Call board?

**Comment by emigbur** [comment]
I Use ESP32 WROVER MODULE
