### ISSUE TITLE
Need connection between Sim800l DTR pin and ESP32

### ISSUE THREAD

**Issue by toomasz** [Xinyuan-LilyGO/TTGO-T-Call#2]
DTR pin from sim800 is used for entering, exiting sleep mode. Is there a connection from it to esp32?
See: 
https://github.com/toomasz/SimcomGsmLib/blob/1e2de6eb4a25372827a03422578f388ed87ab158/src/SimcomAtCommands.cpp#L560

**Comment by vshymanskyy** [comment]
I just uploaded the schematic: https://github.com/Xinyuan-LilyGO/TTGO-T-Call/blob/master/datasheet/TTGO_T-Call_SIM800_v1.3_schematic.pdf

Please let us know about your recommended changes to the schematic for future revisions of the board. Thanks!

**Comment by toomasz** [comment]
@vshymanskyy So I recommend to connect this DTR pin of SIM800l to any free GPIO of esp32 to allow entering exiting sleep mode

**Comment by toomasz** [comment]
Any estimate when next revision will be available?

**Comment by vshymanskyy** [comment]
Ok, closing this as it is already covered by this request: https://github.com/Xinyuan-LilyGO/TTGO-T-Call/issues/13
