### ISSUE TITLE
Number of hardware UART ports?

### ISSUE THREAD

**Issue by pengiundev** [Xinyuan-LilyGO/TTGO-T-Call#22]
Hello, I can't see how many hardware uart ports are available from the pinout. The ESP32 has 3, so one of them taken for the sim800 module tx/rx, means that there should be two, but I'm seeing only one on the pinout?

**Comment by GeirFrimann** [comment]
I have successfully been able to use serial2:
Serial2.begin(115200, SERIAL_8N1, 14, 27);

**Comment by vshymanskyy** [comment]
This is a regular ESP32 chip so you have 3 hw serial ports. Pins can be assigned by software almost arbitrarily.
