### ISSUE TITLE
Set sim power pin 23 high

### ISSUE THREAD

**Issue by crash007** [Xinyuan-LilyGO/TTGO-T-Call#4]
https://github.com/Xinyuan-LilyGO/TTGO-T-Call/blob/6848ddee1c57b1c8b12c7d8b9594519e28801e0f/examples/Arduino_TinyGSM/Arduino_TinyGSM.ino#L65

Shouldnt pin 23 be set to high aswell?
Best regards

**Comment by vshymanskyy** [comment]
I will be re-checking the examples after I get the latest revision of the board.

**Comment by crash007** [comment]
Sounds good. I have order som boards. I can help you test if i receive them before you.

**Comment by crash007** [comment]
I received my modules today and can confirm. I made a small pull request https://github.com/Xinyuan-LilyGO/TTGO-T-Call/pull/5

**Comment by vshymanskyy** [comment]
Thanks. Receiving mine soon. Will test and update. Please check out the GSM OTA example!

**Comment by vshymanskyy** [comment]
The TinyGSM and OTA update examples are updated. Please check them out!
