### ISSUE TITLE
pin number for built in led

### ISSUE THREAD

**Issue by KamilLenica** [Xinyuan-LilyGO/TTGO-T-Call#52]
What is the pin number for onboard LED just below ESP32

i've tried 13 and 16 in Arduino and i can't get it to work

**Comment by maromme** [comment]
it is 13. have a look in the schematic:
https://github.com/Xinyuan-LilyGO/TTGO-T-Call/blob/master/datasheet/TTGO_T-Call_SIM800_v1.3_schematic.pdf
on the last page,  the blue led

**Comment by KamilLenica** [comment]
Yes, that was the approach i took.

Nevermind blink example works on pin 13 i must check my code then. Thanks
