### ISSUE TITLE
Arduino_GSM_OTA - TinyGsmClientSecure() doesn't work with SIM5360

### ISSUE THREAD

**Issue by eabase** [Xinyuan-LilyGO/TTGO-T-Call#9]
Hi,
I understand that your module is HW specific, but I am trying to modify the *Arduino_GSM_OTA.ino* to be compatible with the SimCom SIM5360. Thus we are are trying to fix the TinyGSM relevant library header dependence on [TinyGsmClientSIM5360.h](https://github.com/EnviroDIY/TinyGSM/blob/master/src/TinyGsmClientSIM5360.h). In doing some experiments it seem that the function [TinyGsmClientSecure()](https://github.com/Xinyuan-LilyGO/TTGO-T-Call/blob/master/examples/Arduino_GSM_OTA/Arduino_GSM_OTA.ino#L70) doesn't work. 

Any idea what could be the problem?

If you are interested in extending compatibility, please follow our discussion [HERE](https://github.com/vshymanskyy/TinyGSM/issues/189).

**Comment by vshymanskyy** [comment]
Sorry SIM5360 is out of scope of this repo (at the moment).
